### ISSUE TITLE
esmm数据

### ISSUE THREAD

**Issue by AlexanLee** [yangxudong/deeplearning#2]
麻烦问下你esmm的数据是什么样的？

**Comment by aimiyu** [comment]
https://tianchi.aliyun.com/datalab/dataSet.html?dataId=408

**Comment by yangxudong** [comment]
> 麻烦问下你esmm的数据是什么样的？

是tfrecord格式的，可以参考：https://github.com/yangxudong/deeplearning/tree/master/DIN/data
