### ISSUE TITLE
能否也给出如何从public的dataset转换到tf records/examples 的scripts或code?

### ISSUE THREAD

**Issue by lili-ud** [yangxudong/deeplearning#7]

**Comment by lili-ud** [comment]
对于esmm这个算法

**Comment by a540611121** [comment]
> 对于esmm这个算法

同问，请问您有解决方案可以分享一下吗

**Comment by yangxudong** [comment]
原始数据转换成tfrecord并不复杂，网上的参考资料有很多，你们可以自己实现一下。我的代码中不是针对public dataset的，是特定业务定制的，使用public的dataset是需要修改的。
